import Vue from 'vue'
import {Empty, Popup, DropdownMenu, DropdownItem, Tab, Tabs, Calendar, Icon, Button, Toast, Tabbar, TabbarItem, Search, Swipe, SwipeItem } from 'vant'
Vue.use(Button)
Vue.use(Toast)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Icon)
Vue.use(Calendar)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Popup)
Vue.use(Empty)